templates.locationCollectionTpl = _.template([
    '<div class="top-nav location-nav" id="up-navig">',
        '<span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>',
    '</div>',
    '<div class="content">',
        '<div class="row content-row">',
            '<h1>Locations</h1>',

        '<div class="my-groups form-filter" id="my-location-field">',
            '<input type="checkbox" name="my-location-checkbox" id="my-location" autocomplete="off" />',
            '<div class="btn-group">',
                '<label for="my-location" class="btn btn-warning">',
                    '<span class="glyphicon glyphicon-ok"></span>',
                    '<span> </span>',
                '</label>',
                '<label for="my-location" class="btn btn-default active">',
                    'My location',
                '</label>',
            '</div>',
        '</div>',

        '<div class="my-groups form-filter" id="my-groups-field">',
            '<input type="checkbox" name = "my-groups-checkbox" id="my-groups" autocomplete="off" />',
            '<div class="btn-group">',
                '<label for="my-groups" class="btn btn-warning">',
                    '<span class="glyphicon glyphicon-ok"></span>',
                    '<span> </span>',
                '</label>',
                '<label for="my-groups" class="btn btn-default active">',
                    'My groups',
                '</label>',
            '</div>',
        '</div>',

        '</div>',
        '<div class="searcher col-md-12">',
        '</div>',
        '<div class="col-md-12 locations-list">',
        '</div>',
        '<nav class="content-pagination">',
        '</nav>',
    '</div>',
    '<div class="top-nav location-nav" id="down-navig">',
        '<span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>',
    '</div>'
].join(''));
