templates.weekTpl = _.template([
    '<div class="row">',
        '<div class="col-md-1 main-nav">',
            '<span class="glyphicon glyphicon-chevron-left prevPeriod" aria-hidden="true" ></span>',
        '</div>',
        '<div class="col-md-10">',
            '<h1>Schedule (Group name)</h1>',
        '</div>',
        '<div class="col-md-1 main-nav">',
            '<span class="glyphicon glyphicon-chevron-right nextPeriod" aria-hidden="true"></span>',
        '</div>',
    '</div>',    
    '<table class="table table-bordered table-striped">',
        '<thead>',
            '<tr>',
                '<th></th>',
                '<% for (var j = 0; j < width - 1; j++) { %>',
                    '<th>',
                        '<%= start.format(\'dddd, MM/DD/YYYY\') %>',
                    '</th>',
                    '<% start.add(1, \'d\'); %>',
                '<% } %>',
            '</tr>',
        '</thead>',
        '<tbody>',
            '<% start.subtract(7, \'d\'); %>',
            '<% var morning = startTime.hour(), evening = endTime.hour() %>',
            '<% for (var i = 0; i < (evening - morning)*2; i++) { %>',
                '<tr>',
                    '<td>',
                        '<%= startTime.format(\'HH:mm\') %> - <%= startTime.add(30, \'m\').format(\'HH:mm\') %>',
                    '</td>',
                    '<% startTime.subtract(30, \'m\') %>',                   
                    '<% for (var j = 0; j < width - 1; j++) { %>',
                        '<td class="<%= startTime.format(\'HH-mm\')%>-<%= start.format(\'MM-DD-YYYY\') %>">',
                        '</td>',
                        '<% start.add(1, \'d\'); %>',
                    '<% } %>',
                    '<% startTime.add(30, \'m\') %>',
                    '<% start.subtract(7, \'d\'); %>',
                '</tr>',
            '<% } %>',
        '</tbody>',
    '</table>'
].join(''));