templates.userTpl = _.template([
    '<td><%= name %></td>',
    '<td><%= lastName %></td>',
    '<td><%= role %></td>',
    '<td><%= locationCity %></td>',
    '<td><%= locationCountry %></td>',
    '<td><%= login %></td>',
    '<td>',
        '<button class="btn btn-info edit">Edit</button>',
        '<button class="btn btn-danger delete">Delete</button>',
    '</td>'
].join(''));
templates.usersCollectionTpl = _.template([
    '<thead>',
        '<th>Name</th>',
        '<th>Last Name</th>',
        '<th>Role</th>',
        '<th>Locaiton City</th>',
        '<th>Location Country</th>',
        '<th>Login</th>',
        '<th class="actions">Action</th>',
    '</thead>',
    '<tbody>',
    '</tbody>'
].join(''));
templates.userAddTpl = _.template([
    '<div class="modal fade" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add user</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Name</label>',
                        '<input type="text" class="form-control" name="Name" placeholder="John" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Last Name</label>',
                        '<input type="text" class="form-control" name="LastName" placeholder="Doe" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Role</label>',
                        '<select class="form-control" name="Role">',
                            '<option>Teacher</option>',
                            '<option>Coordinator</option>',
                            '<option>Administrator</option>',
                            '<option>Recruiter</option>',
                            '<option>TSE</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location City</label>',
                        '<input type="text" class="form-control" name="LocationCity" placeholder="Dnipro" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location Country</label>',
                        '<input type="text" class="form-control" name="LocationCountry" placeholder="Ukraine" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Login</label>',
                        '<input type="text" class="form-control" name="Login" placeholder="johndoe" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Password</label>',
                        '<input type="password" class="form-control" name="Password" placeholder="qwerty" aria-describedby="basic-addon1">',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.userEditTpl = _.template([
    '<div class="modal fade"tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Edit user</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label for="name">Name</label>',
                        '<input type="text" class="form-control" id="name" name="Name" placeholder="John" aria-describedby="basic-addon1" value="<%= name %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Last Name</label>',
                        '<input type="text" class="form-control" name="LastName" placeholder="Doe" aria-describedby="basic-addon1" value="<%= lastName %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Role</label>',
                        '<select class="form-control" name="Role">',
                            '<option <% if (role === "Teacher") { %> selected <% } %> >Teacher</option>',
                            '<option <% if (role === "Coordinator") { %> selected <% } %> >Coordinator</option>',
                            '<option <% if (role === "Administrator") { %> selected <% } %> >Administrator</option>',
                            '<option <% if (role === "Recruiter") { %> selected <% } %> >Recruiter</option>',
                            '<option <% if (role === "TSE") { %> selected <% } %> >TSE</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location City</label>',
                        '<input type="text" class="form-control" name="LocationCity" placeholder="Dnipro" aria-describedby="basic-addon1" value="<%= locationCity %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location Country</label>',
                        '<input type="text" class="form-control" name="LocationCountry" placeholder="Ukraine" aria-describedby="basic-addon1" value="<%= locationCountry %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Login</label>',
                        '<input type="text" class="form-control" name="Login" placeholder="johndoe" aria-describedby="basic-addon1" value="<%= login %>">',
                    '</div>',
                    '<button class="btn btn-warning change-password">Change password</button>',
                    '<div class="input-group new-password">',
                        '<label>New Password</label>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));