templates.locationTpl = _.template([
    '<td><%= city %></td>',
    '<td><%= country %></td>',
    '<td>',
        '<button class="btn btn-info edit">Edit</button>',
        '<button class="btn btn-danger delete">Delete</button>',
    '</td>'
].join(''));
templates.locationsCollectionTpl = _.template([
    '<thead>',
        '<th>City</th>',
        '<th>Country</th>',
        '<th class="actions">Action</th>',
    '</thead>',
    '<tbody>',
    '</tbody>'
].join(''));
templates.groupTpl = _.template([
    '<td><%= name %></td>',
    '<td><%= direction %></td>',
    '<td><%= location %></td>',
    '<td><%= startDate %></td>',
    '<td><%= finishDate %></td>',
    '<td><%= status %></td>',
    '<td>',
        '<button class="btn btn-info edit">Edit</button>',
        '<button class="btn btn-danger delete">Delete</button>',
    '</td>'
].join(''));
templates.groupsCollectionTpl = _.template([
    '<thead>',
        '<th>Name</th>',
        '<th>Direction</th>',
        '<th>Location</th>',
        '<th>Start Date</th>',
        '<th>Finish Date</th>',
        '<th>Status</th>',
        '<th class="actions">Action</th>',
    '</thead>',
    '<tbody>',
    '</tbody>'
].join(''));
templates.groupModalAddTpl = _.template([
    '<div class="modal fade" id="groupAdd" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add New Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Group name</label>',
                        '<input type="text" class="form-control" name="GroupName" placeholder="Group name" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location name</label>',
                        '<select class="form-control" name="LocationName">',
                            '<option>Chernivtsi</option>',
                            '<option>Kyiv</option>',
                            '<option>Dnipro</option>',
                            '<option>Sofia</option>',
                            '<option>Rivne</option>',
                            '<option>Ivano-Frankivsk</option>',
                            '<option>Lviv</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Direction</label>',
                        '<select class="form-control" name="Direction">',
                            '<option>.Net</option>',
                            '<option>WebUI</option>',
                            '<option>Java</option>',
                            '<option>QC</option>',
                            '<option>C#</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Start Date</label>',
                        '<input type="text" class="form-control" placeholder="Start Date" id="startDate">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Finish Date</label>',
                        '<input type="text" class="form-control" placeholder="Finish Date" id="finishDate">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Status</label>',
                        '<select class="form-control" name="StatusName">',
                            '<option>Planned</option>',
                            '<option>In progress</option>',
                            '<option>Finished</option>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6 teachers-block">',
                            '<div class="input-group">',
                                '<label>Teachers</label>',
                                '<input type="text" class="form-control" placeholder="Teacher" name="teacher">',
                            '</div>',
                            '<a class="add-teacher">+ Add Teacher</a>',
                        '</div>',
                        '<div class="col-md-6 experts-block">',
                            '<div class="input-group">',
                                '<label>Experts</label>',
                                '<input type="text" class="form-control" placeholder="Experts" name="experts">',
                            '</div>',
                            '<a class="add-expert">+ Add Teacher</a>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary add-new-group">Add</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.groupModalEditTpl = _.template([
    '<div class="modal fade" id="groupEdit" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Edit Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Group name</label>',
                        '<input type="text" class="form-control" name="GroupName" placeholder="Group name" aria-describedby="basic-addon1" value="<%= name %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location name</label>',
                        '<select class="form-control" name="LocationName">',
                            '<option <% if (location === "Kyiv") { %> selected <% } %> >Kyiv</option>',
                            '<option <% if (location === "Lviv") { %> selected <% } %> >Lviv</option>',
                            '<option <% if (location === "Ivano-Frankivsk") { %> selected <% } %> >Ivano-Frankivsk</option>',
                            '<option <% if (location === "Sofia") { %> selected <% } %> >Sofia</option>',
                            '<option <% if (location === "Chernivtsi") { %> selected <% } %> >Chernivtsi</option>',
                            '<option <% if (location === "Dnipro") { %> selected <% } %> >Dnipro</option>',
                            '<option <% if (location === "Rivne") { %> selected <% } %> >Rivne</option>',
                            '<option <% if (location === "Rovno") { %> selected <% } %> >Rovno</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Direction</label>',
                        '<select class="form-control" name="Direction">',
                            '<option <% if (direction === ".Net") { %> selected <% } %> >.Net</option>',
                            '<option <% if (direction === "WebUI") { %> selected <% } %> >WebUI</option>',
                            '<option <% if (direction === "Java") { %> selected <% } %> >Java</option>',
                            '<option <% if (direction === "QC") { %> selected <% } %> >QC</option>',
                            '<option <% if (direction === "C#") { %> selected <% } %> >C#</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Start Date</label>',
                        '<input type="text" class="form-control" placeholder="Start Date" id="startDate" value="<%= startDate %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Finish Date</label>',
                        '<input type="text" class="form-control" placeholder="Finish Date" id="finishDate" value="<%= finishDate %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Status</label>',
                        '<select class="form-control" name="StatusName">',
                            '<option <% if (status === "Planned") { %> selected <% } %> >Planned</option>',
                            '<option <% if (status === "In Progress") { %> selected <% } %> >In Progress</option>',
                            '<option <% if (status === "Finished") { %> selected <% } %> >Finished</option>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6 teachers-block">',
                            '<div class="input-group">',
                                '<label>Teachers</label>',
                                '<input type="text" class="form-control" placeholder="Teacher" name="teacher">',
                            '</div>',
                            '<a class="add-teacher">+ Add Teacher</a>',
                        '</div>',
                        '<div class="col-md-6 experts-block">',
                            '<div class="input-group">',
                                '<label>Experts</label>',
                                '<input type="text" class="form-control" placeholder="Experts" name="experts">',
                            '</div>',
                            '<a class="add-expert">+ Add Teacher</a>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary edit-group">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.locationModalAddTpl = _.template([
    '<div class="modal fade" id="locationAdd" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add New Location</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>City</label>',
                        '<input type="text" class="form-control" name="City" placeholder="Dnipro" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Country</label>',
                        '<input type="text" class="form-control" name="Country" placeholder="Ukraine" aria-describedby="basic-addon1">',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary add-new-location">Add</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.locationModalEditTpl = _.template([
    '<div class="modal fade" id="locationEdit" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Edit Location</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>City</label>',
                        '<input type="text" class="form-control" name="City" placeholder="Dnipro" aria-describedby="basic-addon1" value="<%= city %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Country</label>',
                        '<input type="text" class="form-control" name="Country" placeholder="Ukraine" aria-describedby="basic-addon1" value="<%= country %>">',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary edit-location">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.userTpl = _.template([
    '<td><%= name %></td>',
    '<td><%= lastName %></td>',
    '<td><%= role %></td>',
    '<td><%= locationCity %></td>',
    '<td><%= locationCountry %></td>',
    '<td><%= login %></td>',
    '<td>',
        '<button class="btn btn-info edit">Edit</button>',
        '<button class="btn btn-danger delete">Delete</button>',
    '</td>'
].join(''));
templates.usersCollectionTpl = _.template([
    '<thead>',
        '<th>Name</th>',
        '<th>Last Name</th>',
        '<th>Role</th>',
        '<th>Locaiton City</th>',
        '<th>Location Country</th>',
        '<th>Login</th>',
        '<th class="actions">Action</th>',
    '</thead>',
    '<tbody>',
    '</tbody>'
].join(''));
templates.userAddTpl = _.template([
    '<div class="modal fade" id="userAdd" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add user</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Name</label>',
                        '<input type="text" class="form-control" name="Name" placeholder="John" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Last Name</label>',
                        '<input type="text" class="form-control" name="LastName" placeholder="Doe" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Role</label>',
                        '<select class="form-control" name="Role">',
                            '<option>Teacher</option>',
                            '<option>Coordinator</option>',
                            '<option>Administrator</option>',
                            '<option>Recruiter</option>',
                            '<option>TSE</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location City</label>',
                        '<input type="text" class="form-control" name="LocationCity" placeholder="Dnipro" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location Country</label>',
                        '<input type="text" class="form-control" name="LocationCountry" placeholder="Ukraine" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Login</label>',
                        '<input type="text" class="form-control" name="Login" placeholder="johndoe" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Password</label>',
                        '<input type="password" class="form-control" name="Password" placeholder="qwerty" aria-describedby="basic-addon1">',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));
templates.userEditTpl = _.template([
    '<div class="modal fade" id="userAdd" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add user</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="form-horizontal">',
                        '<div class="form-group">',
                            '<label for="name">Name</label>',
                            '<input type="text" class="form-control" id="name" name="Name" placeholder="John" aria-describedby="basic-addon1" value="<%= name %>">',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Last Name</label>',
                            '<input type="text" class="form-control" name="LastName" placeholder="Doe" aria-describedby="basic-addon1" value="<%= lastName %>">',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Role</label>',
                            '<select class="form-control" name="Role">',
                                '<option <% if (role === "Teacher") { %> selected <% } %> >Teacher</option>',
                                '<option <% if (role === "Coordinator") { %> selected <% } %> >Coordinator</option>',
                                '<option <% if (role === "Administrator") { %> selected <% } %> >Administrator</option>',
                                '<option <% if (role === "Recruiter") { %> selected <% } %> >Recruiter</option>',
                                '<option <% if (role === "TSE") { %> selected <% } %> >TSE</option>',
                            '</select>',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Location City</label>',
                            '<input type="text" class="form-control" name="LocationCity" placeholder="Dnipro" aria-describedby="basic-addon1" value="<%= locationCity %>">',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Location Country</label>',
                            '<input type="text" class="form-control" name="LocationCountry" placeholder="Ukraine" aria-describedby="basic-addon1" value="<%= locationCountry %>">',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Login</label>',
                            '<input type="text" class="form-control" name="Login" placeholder="johndoe" aria-describedby="basic-addon1" value="<%= login %>">',
                        '</div>',
                        '<div class="form-group">',
                            '<label>New Password</label>',
                            '<input type="password" class="form-control" name="Password" placeholder="qwerty" aria-describedby="basic-addon1">',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));