templates.groupAddTpl = _.template([
    '<div class="modal fade" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add New Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Group name</label>',
                        '<input type="text" class="form-control" name="GroupName" placeholder="Group name" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location name</label>',
                        '<select class="form-control" name="LocationName">',
                            '<% locations.forEach(function(currentLocation) { %>',
                                '<option><%= currentLocation.get("city") %></option>',
                            '<% }, this); %>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Direction</label>',
                        '<select class="form-control" name="Direction">',
                            '<option>.Net</option>',
                            '<option>WebUI</option>',
                            '<option>Java</option>',
                            '<option>QC</option>',
                            '<option>C#</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Start Date</label>',
                        '<input type="text" class="form-control" placeholder="Start Date" id="startDate">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Finish Date</label>',
                        '<input type="text" class="form-control" placeholder="Finish Date" id="finishDate">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Status</label>',
                        '<select class="form-control" name="StatusName" disabled>',
                            '<option>Planned</option>',
                            '<option>In progress</option>',
                            '<option>Finished</option>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6 teachers-block">',
                            '<div class="input-group">',
                                '<label>Teachers</label>',
                                '<select class="form-control" multiple name="Teachers">',
                                    '<% allTeachers.forEach(function(currentTeacher) { %>',
                                        '<option><%= currentTeacher.get("lastName") + " " + currentTeacher.get("name") %></option>',
                                    '<% }, this); %>',
                                '</select>',
                            '</div>',
                        '</div>',
                        '<div class="col-md-6 experts-block">',
                            '<div class="input-group">',
                                '<label>Experts</label>',
                                '<input type="text" class="form-control" placeholder="Expert" name="expert">',
                            '</div>',
                            '<a class="add-expert">+ Add Expert</a>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Add</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));