templates.groupModalDeleteTpl = _.template([
    '<div class="modal fade" id="groupDelete" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">You want to delete group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<p>Please confirm, that you want to delete group?</p>',
                '</div>',
                '<div class="modal-footer">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary delete">Delete</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));

templates.groupModalAddTpl = _.template([
    '<div class="modal fade" id="groupAdd" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Add New Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Group name</label>',
                        '<input type="text" class="form-control" name="GroupName"placeholder="Group name" aria-describedby="basic-addon1">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location name</label>',
                        '<select class="form-control">',
                            '<option>Dnipro</option>',
                            '<option>Lviv</option>',
                            '<option>Rovno</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Start Date</label>',
                        '<input type="text" class="form-control" placeholder="Group name" >',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Finish Date</label>',
                        '<input type="text" class="form-control" placeholder="Group name" >',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Status</label>',
                        '<select class="form-control">',
                            '<option>New</option>',
                            '<option>In progress</option>',
                            '<option>Old</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Teachers</label>',
                        '<input type="text" class="form-control" placeholder="Teachers" >',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Experts</label>',
                        '<input type="text" class="form-control" placeholder="Experts" >',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Students</label>',
                        '<input type="text" class="form-control" placeholder="Students" >',
                    '</div>',
                '</div>',
                '<div class="modal-footer">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary add-new-group">Add</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));