templates.groupEditTpl = _.template([
    '<div class="modal fade" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Edit Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="form-horizontal">',
                        '<div class="form-group">',
                            '<label class="col-sm-2 control-label">Group</label>',
                            '<div class="col-sm-10">',
                                '<input type="text" class="form-control" name="GroupName" placeholder="Group name" aria-describedby="basic-addon1" value="<%= name %>">',
                            '</div>',
                        '</div>',
                        '<div class="form-group">',
                            '<label class="col-sm-2 control-label">Location</label>',
                            '<div class="col-sm-10">',
                                '<select class="form-control" name="LocationName">',
                                '<% locations.forEach(function(currentLocation) { %>',
                                    '<% var city = currentLocation.get("city") %>',
                                    '<option ',
                                        '<% if (location === city) { %>',
                                            'selected',
                                        '<% } %>',
                                    ' >',
                                        '<%= city %>',
                                    '</option>',
                                '<% }, this); %>',
                                '</select>',
                            '</div>',
                        '</div>',
                        '<div class="form-group">',
                            '<label class="col-sm-2 control-label">Direction</label>',
                            '<div class="col-sm-10">',
                                '<select class="form-control" name="Direction">',
                                    '<option <% if (direction === ".Net") { %> selected <% } %> >.Net</option>',
                                    '<option <% if (direction === "WebUI") { %> selected <% } %> >WebUI</option>',
                                    '<option <% if (direction === "Java") { %> selected <% } %> >Java</option>',
                                    '<option <% if (direction === "QC") { %> selected <% } %> >QC</option>',
                                    '<option <% if (direction === "C#") { %> selected <% } %> >C#</option>',
                                '</select>',
                            '</div>',
                        '</div>',
                        '<div class="form-group">',
                            '<label class="col-sm-2 control-label">Start</label>',
                            '<div class="col-sm-4">',
                                '<input type="text" class="form-control" placeholder="Start Date" id="startDate">',
                            '</div>',
                            '<label class="col-sm-2 control-label">Finish</label>',
                            '<div class="col-sm-4">',
                                '<input type="text" class="form-control" placeholder="Finish Date" id="finishDate">',
                            '</div>',
                        '</div>',
                        '<div class="form-group">',
                            '<label class="col-sm-2 control-label">Status</label>',
                            '<div class="col-sm-10">',
                                '<select class="form-control" name="StatusName">',
                                    '<option <% if (status === "Planned") { %> selected <% } %> >Planned</option>',
                                    '<option <% if (status === "In Progress") { %> selected <% } %> >In Progress</option>',
                                    '<option <% if (status === "Finished") { %> selected <% } %> >Finished</option>',
                                '</select>',
                            '</div>',
                        '</div>',
                        '<div class="form-group">',
                            '<div class="teachers-block col-sm-6">',
                                '<label class="control-label">Teachers</label>',
                                '<select class="form-control" multiple name="Teachers">',
                                    '<% allTeachers.forEach(function(currentTeacher) { %>',
                                        '<option ',
                                            '<% _.each(teachers, function (val) { %>',
                                                '<% if (val === currentTeacher) { %>',
                                                    'selected',
                                                '<% } %>',
                                            '<% }) %>',
                                        '>',
                                            '<%= currentTeacher %>',
                                        '</option>',
                                    '<% }, this); %>',
                                '</select>',
                            '</div>',
                            '<div class="experts-block col-sm-6">',
                                '<label class="control-label">Experts</label>',
                                '<% _.each(experts, function (val) { %>',
                                    '<input type="text" class="form-control" placeholder="Expert" name="expert" value="<%= val %>">',
                                '<% }) %>',
                                '<a class="add-expert">+ Add Expert</a>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default close-btn">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));