templates.groupEditTpl = _.template([
    '<div class="modal fade" tabindex="-1" role="dialog">',
        '<div class="modal-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
                    '<h4 class="modal-title">Edit Group</h4>',
                '</div>',
                '<div class="modal-body">',
                    '<div class="input-group">',
                        '<label>Group name</label>',
                        '<input type="text" class="form-control" name="GroupName" placeholder="Group name" aria-describedby="basic-addon1" value="<%= name %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Location name</label>',
                        '<select class="form-control" name="LocationName">',
                            '<% locations.forEach(function(currentLocation) { %>',
                                '<option <% if (location === currentLocation.get("city")) { %> selected <% } %> >',
                                '<%= currentLocation.get("city") %></option>',
                            '<% }, this); %>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Direction</label>',
                        '<select class="form-control" name="Direction">',
                            '<option <% if (direction === ".Net") { %> selected <% } %> >.Net</option>',
                            '<option <% if (direction === "WebUI") { %> selected <% } %> >WebUI</option>',
                            '<option <% if (direction === "Java") { %> selected <% } %> >Java</option>',
                            '<option <% if (direction === "QC") { %> selected <% } %> >QC</option>',
                            '<option <% if (direction === "C#") { %> selected <% } %> >C#</option>',
                        '</select>',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Start Date</label>',
                        '<input type="text" class="form-control" placeholder="Start Date" id="startDate" value="<%= startDate %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Finish Date</label>',
                        '<input type="text" class="form-control" placeholder="Finish Date" id="finishDate" value="<%= finishDate %>">',
                    '</div>',
                    '<div class="input-group">',
                        '<label>Status</label>',
                        '<select class="form-control" name="StatusName">',
                            '<option <% if (status === "Planned") { %> selected <% } %> >Planned</option>',
                            '<option <% if (status === "In Progress") { %> selected <% } %> >In Progress</option>',
                            '<option <% if (status === "Finished") { %> selected <% } %> >Finished</option>',
                        '</select>',
                    '</div>',
                    '<div class="row">',
                        '<div class="col-md-6 teachers-block">',
                            '<div class="input-group">',
                                '<label>Teachers</label>',
                                '<% _.each(teachers, function (val) { %>',
                                    '<input type="text" class="form-control" placeholder="Teacher" name="teacher" value="<%= val %>">',
                                '<% }) %>',
                            '</div>',
                            '<a class="add-teacher">+ Add Teacher</a>',
                        '</div>',
                        '<div class="col-md-6 experts-block">',
                            '<div class="input-group">',
                                '<label>Experts</label>',
                                '<% _.each(experts, function (val) { %>',
                                    '<input type="text" class="form-control" placeholder="Expert" name="expert" value="<%= val %>">',
                                '<% }) %>',
                            '</div>',
                            '<a class="add-expert">+ Add Expert</a>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="modal-footer clearfix">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary submit">Submit</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));