templates.editViewTpl = _.template([
        '<div class="event-type">',
            '<label class="edit-panel-labels">Event Type</label>',
            '<select class="form-control" name="eventType" id = "event-type">',
                '<% types.forEach(function(type) { %>',
                    '<option><%= type %></option>',
                '<% }, this); %>',
            '</select>',
        '</div>',
        '<div class = "offices">',
            '<label class="edit-panel-labels">Office</label>',
            '<div class="btn-group" data-toggle="buttons" name="OfficeName" id="offices">',
                '<% if (offices) { %>',
                    '<% offices.forEach(function(office) { %>',
                        '<label class="btn btn-primary ',
                            '<% if (office.get("_id") === officeId) { %>',
                                'active',
                            '<% } %>',
                            '" >',
                            '<input type="radio" name="options"',
                                ' id="',
                                    '<%= "ofice_" + office.get("_id") %>',
                                '"',
                                ' autocomplete="off">',
                            '<span><%= office.get("name") %></span>',
                        '</label>',
                    '<% }, this); %>',
                '<% } %>',
            '</div>',
        '</div>',
        '<div class = "rooms">',
            '<label class="edit-panel-labels">Room</label>',
            '<div class="btn-group" data-toggle="buttons" name="RoomName" id="rooms">',
                '<% if (rooms) { %>',
                    '<% rooms.forEach(function(room) { %>',
                        '<label class="btn btn-primary ',
                            '<% if (room.get("_id") === roomId) { %>',
                                'active',
                            '<% } %>',
                        '"  data-room-id="<%= room.get("_id") %>">',
                            '<input type="radio" name="options"',
                                ' id="',
                                    '<%= "room_" + room.get("_id") %>',
                                '"',
                                ' autocomplete="off">',
                            '<span><%= room.get("name") %></span>',
                        '</label>',
                    '<% }, this); %>',
                '<% } %>',
            '</div>',
        '</div>'
].join(''));