templates.editViewTpl = _.template([
    '<div class="top-nav location-nav" id="up-navig">',
        '<span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>',
    '</div>',
    '<h1>Schedule</h1>',
    '<div class = "row">',
    '<div class="col-md-2">',
        '<label>Event Type</label>',
        '<select class="form-control" name="OfficeName">',
            '<% types.forEach(function(type) { %>',
                '<option><%= type %></option>',
            '<% }, this); %>',
        '</select>',
    '</div>',
    '<% if (groups) { %>',
        '<div class="col-md-2">',
            '<label>Group</label>',
            '<select class="form-control" name="GroupName">',
                '<% groups.forEach(function(group) { %>',
                    '<option><%= group.get("name") %></option>',
                '<% }, this); %>',
            '</select>',
        '</div>',
    '<% } %>',
    '<div class="col-md-2">',
        '<label>Office</label>',
        '<select class="form-control" name="OfficeName">',
            '<% offices.forEach(function(office) { %>',
                '<option><%= office.get("name") %></option>',
            '<% }, this); %>',
        '</select>',
    '</div>',
    '<div class="col-md-2">',
        '<label>Room</label>',
        '<select class="form-control" name="RoomName">',
            '<% rooms.forEach(function(room) { %>',
                '<option><%= room.get("name") %></option>',
            '<% }, this); %>',
        '</select>',
    '</div>',
    '</div>'
].join(''));